name: GitHub CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        composer-type: [lowest highest]
        db-type: [sqlite, mysql, pgsql]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Create DB
        run: if [ ${{ matrix.db-type }} == 'mysql' ]; then mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_fixture_factories;'; fi

      - name: Validate composer.json
        run: composer validate

      - if: ${{ matrix.composer-type }} == 'lowest'
        name: Install lowest dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-lowest --prefer-stable

      - if: ${{ matrix.composer-type }} == 'highest'
        name: Install highest dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable

      - if: ${{ matrix.db-type }} == 'sqlite'
        name: Run tests on sqlite
        run: composer run-tests-sqlite

      - if: ${{ matrix.db-type }} == 'mysql'
        name: Run tests on mysql
        run: composer run-tests-mysql root root

      - if: ${{ matrix.db-type }} == 'postgres'
        name: Run tests on postgres
        run: composer run-tests-postgres postgres postgres